import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import {
  Bot,
  Check,
  ChevronDown,
  ChevronUp,
  CircleSlash,
  ClipboardPaste,
  Clock,
  Code,
  Download,
  Flame,
  FlaskConical,
  CircleQuestionMark,
  GitPullRequest,
  Inbox,
  Info,
  LibraryBig,
  Lightbulb,
  ListChecks,
  LogOut,
  LucideAngularModule,
  MessageSquare,
  Plus,
  Repeat,
  Search,
  ShieldCheck,
  Sparkles,
  Swords,
  Tag,
  Tags,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  Users,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        Bot,
        Check,
        ChevronDown,
        ChevronUp,
        CircleSlash,
        ClipboardPaste,
        Clock,
        Code,
        Download,
        Flame,
        FlaskConical,
        CircleQuestionMark,
        GitPullRequest,
        Inbox,
        Info,
        LibraryBig,
        Lightbulb,
        ListChecks,
        LogOut,
        MessageSquare,
        Plus,
        Repeat,
        Search,
        ShieldCheck,
        Sparkles,
        Swords,
        Tag,
        Tags,
        TrendingUp,
        TriangleAlert,
        Upload,
        User,
        Users,
        X,
      }),
    ),
  ],
};
