services:
  db:
    image: postgres:16-alpine
    container_name: postgres_common_ground
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_pwd
      - POSTGRES_DB=common_ground
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d common_ground"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: