package com.mitchelnijdam.commonground.rankings

import com.mitchelnijdam.commonground.pattern.Pattern
import com.mitchelnijdam.commonground.pattern.PatternRepository
import com.mitchelnijdam.commonground.topic.Topic
import com.mitchelnijdam.commonground.topic.TopicRepository
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional

enum class ExportFormat(val filename: String) {
    GENERIC("common-ground.md"),
    CLAUDE("CLAUDE.md"),
    COPILOT("copilot-instructions.md"),
    CURSOR("coding-standards.mdc"),
    WINDSURF(".windsurfrules"),
}

@Service
class MarkdownExportService(
    private val topicRepository: TopicRepository,
    private val patternRepository: PatternRepository,
) {

    @Transactional(readOnly = true)
    fun export(format: ExportFormat = ExportFormat.GENERIC): String {
        val activePatternsByTopic = patternRepository.findByActiveTrue().groupBy { it.topic.id }

        val sections = topicRepository.findAll()
            .sortedBy { it.id }
            .mapNotNull { topic ->
                val patterns = activePatternsByTopic[topic.id].orEmpty()
                if (patterns.none { it.timesShown > 0 }) return@mapNotNull null
                val winner = patterns.sortedWith(
                    compareByDescending<Pattern> { it.eloRating }.thenBy { it.id },
                ).first()
                section(topic, winner)
            }

        return buildString {
            if (format == ExportFormat.CURSOR) {
                append("---\ndescription: Team coding standards voted on Common Ground\nalwaysApply: true\n---\n\n")
            }
            append("# Coding Standards\n\n")
            append("Team-voted coding standards generated by Common Ground.")
            append(" These represent the preferred patterns selected by community vote.\n\n")
            append("---\n\n")
            append(sections.joinToString("\n\n", postfix = "\n"))
        }
    }

    private fun section(topic: Topic, winner: Pattern): String = buildString {
        append("## ").append(topic.question).append("\n")
        if (!topic.context.isNullOrBlank()) {
            append("\n> ").append(topic.context).append("\n")
        }
        append("\n**").append(winner.title).append("**\n\n")
        append("```").append(topic.language.orEmpty()).append("\n")
        append(winner.code.trimEnd('\n')).append("\n")
        append("```")
    }
}
